#+OPTIONS: html-postamble:nil toc:nil
#+EXPORT_FILE_NAME: options.html

This is a Emacs key binding addon for Firefox 57+. These keybindings work in most webpages, but not in internal Firefox pages ('about:xxxx', new tab page).

Due to limitations of the current extension interface it is not possible to change keybindings for the Firefox user interface itself - and overriding only works for some of the keys, varying between platforms. If bindings are not working please check the [[./doc/troubleshooting.org][troubleshooting guide]] for tips on how to change Firefox configuration no disable conflicting Firefox bindings.

Shortcomings of the extension interface also require a page to have fully loaded before keybindings can work - i.e., adding a keybinding for aborting loading of a new tab is not possible. Future versions may try workarounds for some keybindings by defining command keys.

For reporting problems please use the [[https://github.com/bwachter/emacs-keybinding/issues][Github issue tracker]]. The [[./doc/index.org][developer documentation]] is useful if you want to contribute to this extension.

* Keybindings
Note that bindings without modifier keys are disabled per default. C-n/C-p causes the most issues - see the [[./doc/troubleshooting.org][troubleshooting guide]].

** Scroll

| keymap   | description      |
|----------+------------------|
| C-n or n | scroll down      |
| C-p or p | scroll up        |
| C-f      | scroll right     |
| C-b      | scroll left      |
| M-<      | scroll to top    |
| M->      | scroll to bottom |

** Tab

| keymap  | description                   |
|---------+-------------------------------|
| M-f     | next tab                      |
| M-b     | previous tab                  |
| C-x C-f | new tab                       |
| C-x k   | close current tab             |
| t       | focus on the first input area |

** Window

| keymap      | description          |
|-------------+----------------------|
| C-u C-x C-f | new window           |
| C-u C-x k   | close current window |

** Others

| keymap | description                |
|--------+----------------------------|
| C-g    | focus on window            |
| C-r    | refresh                    |
| C-F    | history forward            |
| C-B    | history back               |
| C-h ?  | display help/settings page |

* Configuration

#+BEGIN_EXPORT html
<form>
<label><input type="checkbox" name="own_tab_page" id="own_tab_page"/> Use custom 'new tab' page to allow overriding keybindings</label><br/>
<label><input type="checkbox" name="debug_log" id="debug_log"/> Log debug messages to console</label><br/>
<label><input type="checkbox" name="bindings_without_modifier" id="bindings_without_modifier"/> Allow top level keybindings without modifier</label><br/>
<label><input type="checkbox" name="experimental" id="experimental"/> Enable experimental features</label><br/>
<!--
<fieldset>
<label><input type="radio" name="preferred_input" id="prefer_dialog" value="dialog"> Prefer HTML dialogs</label><br/>
<label><input type="radio" name="preferred_input" id="prefer_popup" value="popup"> Prefer browser action popup</label><br/>
</fieldset>
-->
</form>

<script src="jquery-3.7.0.min.js"></script>
<script src="options.js"></script>
#+END_EXPORT
