#+OPTIONS: html-postamble:nil toc:nil
#+EXPORT_FILE_NAME: troubleshooting

[[../options.org][Add-on settings]]

* Setup and troubleshooting
On recent Firefox versions this extension seems to be shadowing global Firefox keybindings. If this is not the case on your version the easiest way to free those keybindings is to change the access key used by Firefox, either by setting [[http://kb.mozillazine.org/Ui.key.chromeAccess][Ui.key.chromeAccesss]] or [[http://kb.mozillazine.org/Ui.key.generalAccessKey][Ui.key.generalAccessKey]] in [[https://support.mozilla.org/fi/kb/about-config-editor-firefox][about:config]].

This extension now registers as an action to enable developing some more features. Interacting with the action button is optional - you can remove the button from the toolbar if you're not interested in using it.

Firefox has a built in code editor. The keymap for this can be set by configuring [[https://firefox-source-docs.mozilla.org/devtools-user/keyboard_shortcuts/index.html][devtools.editor.keymap]] to "emacs".

** Emacs bindings in Firefox UI and text fields
This extension can't change keybindings in the Firefox UI, and currently does not have keybindings for text fields. Depending on the operating system used this can be partially fixed, though.

*** Windows
Some keybindings can be configured with the [[https://github.com/catweazle9/emacs-everywhere][emacs-everywhere]] [[https://www.autohotkey.com/][AutoHotkey]] script.

*** Linux
On Linux Firefox uses GTK - which comes with basic support for Emacs keybindings. =~/.config/gtk-3.0/settings.ini= should contain the following:

#+BEGIN_EXAMPLE
[Settings]
gtk-key-theme-name = Emacs
#+END_EXAMPLE

Additionally the same key should be set in gsettings:

#+BEGIN_EXAMPLE
gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
#+END_EXAMPLE
